services:
  db:
    image: postgres:16
    container_name: shop_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: shop_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=HW_website.settings
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
